spring:
  application:
    name: task-tracker
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
