apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: task-tracker
type: Opaque
stringData:
  TASK_TRACKER_DATABASE_NAME: task_tracker
  TASK_TRACKER_DATABASE_USER: postgres
  TASK_TRACKER_DATABASE_PASSWORD: "1234"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: task-tracker
type: Opaque
stringData:
  TASK_TRACKER_RABBITMQ_USER: guest
  TASK_TRACKER_RABBITMQ_PASSWORD: guest
---
apiVersion: v1
kind: Secret
metadata:
  name: mailgun-secret
  namespace: task-tracker
type: Opaque
stringData:
  MG_DOMAIN: "your-mailgun-domain"
  MG_API_KEY: "your-mailgun-api-key"